import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"], weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-nunitoSans'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunitoSans.variable}>{children}</body>
    </html>
  );
}
